CFP.Web/Controllers/DashboardController.cs
using System.Diagnostics;
using CFP.Common.Utility;
using CFP.Patient.Controllers;
using CFP.Provider.IProvider;
using CFP.Provider.Provider;
using CFP.Web.Filter;
using CFP.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace CFP.Web.Controllers
{
    [Authorization(MenuId = 1)]
    public class DashboardController : BaseController
    {

        #region Variables
        IUserMasterProvider _userProvider;
        #endregion

        #region Constructor
        public DashboardController(ICommonProvider commonProvider, ISessionManager sessionManager, IUserMasterProvider userProvider) : base(commonProvider, sessionManager)
        {
            _userProvider = userProvider;
        }
        #endregion

        #region Methods
        public IActionResult Index()
        {
            ViewBag.IsAuthenticated = User.Identity.IsAuthenticated;
            DashboardViewModel model = new DashboardViewModel()
            {
                RoleId = _sessionManager.RoleId,
                AgentId = _sessionManager.AgentId,
                DealCount = _commonProvider.GetDealCount(GetSessionProviderParameters()),
                DealSummaryList = _commonProvider.GetDealSummary(),
                AgentList = GetAgentList()
            };
            return View(model);
        }
        public JsonResult SaveTempFilter(string KitId, string PatientId)
        {
            SetDataInTemp(AppCommon.TMP_ENC_KIT_ID, KitId);
            SetDataInTemp(AppCommon.TMP_ENC_PATIENT_ID, PatientId);
            return Json(true);
        }
        public JsonResult LeaderBoard()
        {
            return Json(_commonProvider.GetLeaderBoard().Select(x => new { x.Text, x.ExtraValue }).OrderByDescending(x => x.ExtraValue).ToList());
        }
        public JsonResult FetchDealData(int agentId)
        {
            var chartData = _commonProvider.GetDealDataForChart(agentId);
            var payload = chartData.Select(d => new
            {
                date = d.Date.ToString("MM/dd/yyyy"), // consistent client format
                label = d.DateLabel,
                applicantCount = d.ApplicantCount,
                dealCount = d.DealCount,
                agentCount=d.AgentCount
            }).ToList();
            return Json(payload);
        }

        [HttpPost]
        public JsonResult FetchDealDataAllAgents(int days)
        {
            return Json(_commonProvider.GetAgentDealDashboard(days));
        }

        #endregion
    }
}

CFP.Web/ViewComponents/MenuViewComponent.cs
using CFP.Common.Utility;
using CFP.Provider.IProvider;
using Microsoft.AspNetCore.Mvc;

namespace CFP.Web.ViewComponents
{
    [ViewComponent(Name = "Menu")]
    public class MenuViewComponent : ViewComponent
    {
        public ISessionManager _sessionManager = null;
        ICommonProvider _commonProvider;

        public MenuViewComponent(ISessionManager sessionManager, ICommonProvider commonProvider)
        {
            _sessionManager = sessionManager;
            _commonProvider = commonProvider;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var list = _commonProvider.GetMenuList(
                new Common.Common_Entities.SessionProviderModel()
                {
                    UserId = _sessionManager.UserId,
                    RoleId = _sessionManager.RoleId
                });
            return View(list);
        }

    }
}

CFP.Web/ViewComponents/UserNameHeaderViewComponent.cs
using CFP.Common.Business_Entities;
using CFP.Common.Utility;
using CFP.Provider.IProvider;
using Microsoft.AspNetCore.Mvc;

namespace CFP.Web.ViewComponents
{

    [ViewComponent(Name = "UserNameHeader")]
    public class UserNameHeaderViewComponent : ViewComponent
    {
        public ISessionManager _sessionManager = null;
        IUserMasterProvider _userMasterProvider;

        public UserNameHeaderViewComponent( ISessionManager sessionManager, IUserMasterProvider userMasterProvider)
        {
            _sessionManager = sessionManager;
            _userMasterProvider = userMasterProvider;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            UserHeaderDetailModel model = new UserHeaderDetailModel();
            if (_sessionManager.UserId > 0)
            {
                var userDetails = _userMasterProvider.GetById(_sessionManager.UserId);
                if (userDetails != null)
                {
                    model.Username = userDetails.Username;
                    model.FirstName = userDetails.FirstName;
                    model.LastName = userDetails.LastName;
                    model.UserMasterId = userDetails.UserMasterId;
                    model.RoleId = userDetails.RoleId;
                    model.RoleName = userDetails.RoleName;
                }
            }
            return View(model);
        }

    }
}

CFP.Web/Views/Shared/_AdminBreadcumb.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

CFP.Web/Views/Shared/_FooterScriptPartial.cshtml
<!-- JAVASCRIPT -->
<script src="/assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/assets/libs/simplebar/simplebar.min.js"></script>
<script src="/assets/libs/node-waves/waves.min.js"></script>
<script src="/assets/libs/feather-icons/feather.min.js"></script>
<script src="/assets/js/pages/plugins/lord-icon-2.1.0.js"></script>
<script src="/assets/js/plugins.js"></script><script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
@* <script type="text/javascript" src="assets/libs/choices.js/public/assets/scripts/choices.min.js"></script> *@
<script type="text/javascript" src="assets/libs/flatpickr/flatpickr.min.js"></script>



<!-- apexcharts -->
<script src="/assets/libs/apexcharts/apexcharts.min.js"></script>

<!-- Swiper Js -->
<script src="/assets/libs/swiper/swiper-bundle.min.js"></script>

<!-- CRM js -->
<script src="/assets/js/pages/dashboard-crypto.init.js"></script>

<!-- App js -->
<script src="/assets/js/app.js"></script>

<script src="~/assets/js/jquery.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<!-- prismjs plugin -->
<script src="/assets/libs/prismjs/prism.js"></script>

<!-- init js -->
<script src="~/assets/js/pages/form-pickers.init.js"></script>


<!-- App js -->
<script src="/assets/js/app.js"></script>

<script src="~/assets/js/jquery.validate.min.js"></script>
<script src="~/assets/js/jquery.validate.unobtrusive.js"></script>

<script src="~/assets/js/jquery.inputmask.bundle.js"></script>
<script src="~/assets/js/jquery.inputmask.bundle.min.js"></script>

<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>

<!--datatable js-->
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.html5.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/7.0.0/signalr.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js" asp-append-version="true"></script>

<script src="~/assets/js/toastr.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="~/assets/libs/flatpickr/flatpickr.min.js"></script>
@* <script src="~/assets/libs/flatpickr/flatpickr.min.js"></script> *@

<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

<script src="~/lib/js/custom/CFP.js" asp-append-version="true"></script>
<script src="~/lib/js/custom/CFP.common.js" asp-append-version="true"></script>
<script src="~/lib/js/custom/CFP.ChatClient.js" asp-append-version="true"></script>
@* <script src="~/lib/js/custom/CFP.Enum.js" asp-append-version="true"></script> *@

<script>
        window.isAuthenticated = @User.Identity.IsAuthenticated.ToString().ToLower();

    function UrlContent(url) {
        return "@Url.Content("~/")" + url
    }
    $(".pwd").click(function () {
        if ($(this).children().hasClass("fa fa-eye")) {
            $(this).children().removeClass().addClass("fa fa-eye-slash");
            $(this).parent().next().attr("type", "text");
        }
        else {
            $(this).children().removeClass().addClass("fa fa-eye");
            $(this).parent().next().attr("type", "password");
        }
    });
    $(document).ready(function () {
        $(".preloader").hide();
        initActiveMenu();
   
        $("#topnav-hamburger-icon").click(function (e) {
            var windowSize = document.documentElement.clientWidth;

        if (windowSize > 767)
            document.querySelector(".hamburger-icon").classList.toggle("open");

        //For collapse horizontal menu
        if (document.documentElement.getAttribute("data-layout") === "horizontal") {
            document.body.classList.contains("menu") ? document.body.classList.remove("menu") : document.body.classList.add("menu");
        }

        //For collapse vertical menu
        if (document.documentElement.getAttribute("data-layout") === "vertical") {
            if (windowSize <= 1025 && windowSize > 767) {
                document.body.classList.remove("vertical-sidebar-enable");
                document.documentElement.getAttribute("data-sidebar-size") == "sm" ?
                    document.documentElement.setAttribute("data-sidebar-size", "") :
                    document.documentElement.setAttribute("data-sidebar-size", "sm");
            } else if (windowSize > 1025) {
                document.body.classList.remove("vertical-sidebar-enable");
                document.documentElement.getAttribute("data-sidebar-size") == "lg" ?
                    document.documentElement.setAttribute("data-sidebar-size", "sm") :
                    document.documentElement.setAttribute("data-sidebar-size", "lg");
            } else if (windowSize <= 767) {
                document.body.classList.add("vertical-sidebar-enable");
                document.documentElement.setAttribute("data-sidebar-size", "lg");
            }
        }
            // // debugger;
            // var windowSize = document.documentElement.clientWidth;

            // if (windowSize > 767)
            //     document.querySelector(".hamburger-icon").classList.toggle("open");

            // //For collapse horizontal menu
            // if (document.documentElement.getAttribute("data-layout") === "vertical") {
            //     document.body.classList.contains("menu") ? document.body.classList.remove("menu") : document.body.classList.add("menu");
            // }

        });
        if (window.isAuthenticated) {
            CFP.ChatClient.StartConnection();
        }
    })

    $(document).ajaxError(function (event, request, settings) {
        if (request.status == 401) {
            window.top.location.href = UrlContent("Account/Logout");
        }
        else if (request.status == 403) { //|| request.status == 500
            window.top.location.href = UrlContent("Account/Logout");
        }
    });

    function initActiveMenu() {
        var currentPath = location.pathname == "/" ? "/Dashboard/Index" : location.pathname.substring(1);
        if (currentPath) {
            // navbar-nav
            var a = document.getElementById("navbar-nav").querySelector('[href="' + "/" + currentPath + '"]');
            if (a) {
                a.classList.add("active");
                var parentCollapseDiv = a.closest(".collapse.menu-dropdown");
                if (parentCollapseDiv) {
                    parentCollapseDiv.classList.add("show");
                    parentCollapseDiv.parentElement.children[0].classList.add("active");
                    parentCollapseDiv.parentElement.children[0].setAttribute("aria-expanded", "true");
                    if (parentCollapseDiv.parentElement.closest(".collapse.menu-dropdown")) {
                        parentCollapseDiv.parentElement.closest(".collapse").classList.add("show");
                        if (parentCollapseDiv.parentElement.closest(".collapse").previousElementSibling)
                            parentCollapseDiv.parentElement.closest(".collapse").previousElementSibling.classList.add("active");

                        if (parentCollapseDiv.parentElement.parentElement.parentElement.parentElement.closest(".collapse.menu-dropdown")) {
                            parentCollapseDiv.parentElement.parentElement.parentElement.parentElement.closest(".collapse").classList.add("show");
                            if (parentCollapseDiv.parentElement.parentElement.parentElement.parentElement.closest(".collapse").previousElementSibling) {

                                parentCollapseDiv.parentElement.parentElement.parentElement.parentElement.closest(".collapse").previousElementSibling.classList.add("active");
                                if ((document.documentElement.getAttribute("data-layout") == "horizontal") && parentCollapseDiv.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.closest(".collapse")) {
                                    parentCollapseDiv.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.closest(".collapse").previousElementSibling.classList.add("active")
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    function flatpicker() {
        var flatpickrExamples = document.querySelectorAll("[data-provider]");
        Array.from(flatpickrExamples).forEach(function (item) {
            if (item.getAttribute("data-provider") == "flatpickr") {
                var dateData = {};
                var isFlatpickerVal = item.attributes;
                dateData.disableMobile = "true";
                if (isFlatpickerVal["data-date-format"])
                    dateData.dateFormat = isFlatpickerVal["data-date-format"].value.toString();
                if (isFlatpickerVal["data-enable-time"]) {
                    (dateData.enableTime = true),
                        (dateData.dateFormat = isFlatpickerVal["data-date-format"].value.toString() + " H:i");
                }
                if (isFlatpickerVal["data-altFormat"]) {
                    (dateData.altInput = true),
                        (dateData.altFormat = isFlatpickerVal["data-altFormat"].value.toString());
                }
                if (isFlatpickerVal["data-minDate"]) {
                    dateData.minDate = isFlatpickerVal["data-minDate"].value.toString();
                    dateData.dateFormat = isFlatpickerVal["data-date-format"].value.toString();
                }
                if (isFlatpickerVal["data-maxDate"]) {
                    dateData.maxDate = isFlatpickerVal["data-maxDate"].value.toString();
                    dateData.dateFormat = isFlatpickerVal["data-date-format"].value.toString();
                }
                if (isFlatpickerVal["data-deafult-date"]) {
                    dateData.defaultDate = isFlatpickerVal["data-deafult-date"].value.toString();
                    dateData.dateFormat = isFlatpickerVal["data-date-format"].value.toString();
                }
                if (isFlatpickerVal["data-multiple-date"]) {
                    dateData.mode = "multiple";
                    dateData.dateFormat = isFlatpickerVal["data-date-format"].value.toString();
                }
                if (isFlatpickerVal["data-range-date"]) {
                    dateData.mode = "range";
                    dateData.dateFormat = isFlatpickerVal["data-date-format"].value.toString();
                }
                if (isFlatpickerVal["data-inline-date"]) {
                    (dateData.inline = true),
                        (dateData.defaultDate = isFlatpickerVal["data-deafult-date"].value.toString());
                    dateData.dateFormat = isFlatpickerVal["data-date-format"].value.toString();
                }
                if (isFlatpickerVal["data-disable-date"]) {
                    var dates = [];
                    dates.push(isFlatpickerVal["data-disable-date"].value);
                    dateData.disable = dates.toString().split(",");
                }
                if (isFlatpickerVal["data-week-number"]) {
                    var dates = [];
                    dates.push(isFlatpickerVal["data-week-number"].value);
                    dateData.weekNumbers = true
                }
                flatpickr(item, dateData);
            }
        });
    }
</script>

CFP.Web/Views/Shared/_Header.cshtml
<header id="page-topbar">
    <div class="layout-width">
        <div class="navbar-header">
            <div class="d-flex">
                <!-- LOGO -->                
                <div class="navbar-brand-box horizontal-logo">
                    <a asp-action="Index" asp-controller="Dashboard" class="logo logo-dark" style="margin:10px;">
                        <span class="logo-sm">
                            <img src="~/assets/images/logo-sm.png" alt="" height="22">
                        </span>
                        <span class="logo-lg">
                            <h1 style="font-weight:900">CFP</h1>
                        </span>
                    </a>
                    <!-- Light Logo-->
                    <a asp-action="Index" asp-controller="Dashboard" class="logo logo-light" style="margin:10px;">
                        <span class="logo-sm">
                            <img src="~/assets/images/logo-sm.png" alt="" height="22">
                        </span>
                        <span class="logo-lg">
                            <h1 class="text-white" style="font-weight:900">CFP</h1>
                        </span>
                    </a>
                </div>

                <button type="button" class="btn btn-sm px-3 fs-16 vertical-menu-btn topnav-hamburger" id="topnav-hamburger-icon">
                    <span class="hamburger-icon">
                        <span></span>
                        <span></span>
                        <span></span>
                    </span>
                </button>
            </div>
            <div class="d-flex align-items-center">
                @await Component.InvokeAsync("UserNameHeader")
            </div>
        </div>
    </div>
</header>

CFP.Web/Views/Shared/_HeaderScriptPartial.cshtml
@using CFP.Common.Utility
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta content="@AppCommon.ApplicationTitle" name="description" />
<meta content="Insurance Policy" name="author" />
<!-- App favicon -->
<link rel="shortcut icon" href="~/assets/images/favicon.ico">

<link href="/assets/libs/swiper/swiper-bundle.min.css" rel="stylesheet">

<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

<!-- Layout config Js -->
<script src="/assets/js/layout.js"></script>
<!-- Bootstrap Css -->
<link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<!-- Icons Css -->
<link href="/assets/css/icons.min.css" rel="stylesheet" type="text/css">
<!-- App Css-->
<link href="/assets/css/app.min.css" rel="stylesheet" type="text/css">
<!-- custom Css-->
<link href="/assets/css/custom.min.css" rel="stylesheet" type="text/css">
<!-- custom Css-->
<link href="~/assets/css/toastr.min.css" rel="stylesheet" />
<link rel="stylesheet" href="~/assets/libs/glightbox/css/glightbox.min.css">
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet">

<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" />
<!--datatable responsive css-->
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap.min.css" />
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css">
<link href="~/assets/css/custom.css" rel="stylesheet" asp-append-version="true"/>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

CFP.Web/Views/Shared/_Layout.cshtml
@using CFP.Common.Utility
@* <html lang="en" data-layout="horizontal" data-layout-style="detached" data-sidebar="light" data-topbar="light" data-sidebar-size="lg" data-sidebar-image="none" data-preloader="enable" data-bs-theme="light" data-layout-width="fluid" data-layout-position="fixed" data-sidebar-visibility="show"> *@
<html lang="en" data-layout="vertical" data-layout-style="default" data-sidebar="light" data-topbar="light" data-sidebar-size="lg" data-sidebar-image="none" data-preloader="enable" data-bs-theme="light" data-layout-width="fluid" data-layout-position="fixed" data-sidebar-visibility="show">

<head>
	@RenderSection("CSS", required: false)
	@await Html.PartialAsync("_HeaderScriptPartial")
	<title>@AppCommon.ApplicationTitle - @ViewData["Title"] </title>
	@RenderSection("Style", required: false)
</head>
<body class="">
	<div class="preloader" style="margin: 0 auto;position: absolute;z-index: 9998;height: 100%;width: 100%;opacity: 0.5;">
		<div class="spinner-grow" style="width: 5rem; height: 5rem;position: absolute;left: 50%;top: 50%;" role="status">
			<span class="sr-only">Loading...</span>
		</div>
	</div>
	@{
		var controller = ViewContext.RouteData.Values["controller"]?.ToString();
		if (!(!string.IsNullOrEmpty(controller) && controller.Trim() == "Chat"))
		{
			<style>
				.jump-icon {
					display: inline-block;
					animation: jump 1.2s infinite ease-in-out;
				}

				@@keyframes jump {
					0% {
						transform: translateY(0);
					}

					20% {
						transform: translateY(-10px);
					}

					40% {
						transform: translateY(0);
					}

					60% {
						transform: translateY(-6px);
					}

					80% {
						transform: translateY(0);
					}

					100% {
						transform: translateY(0);
					}
				}
			</style>
			<div class="customizer-setting d-none d-md-block">
				<a href="@(Url.Content("Chat"))">
					<span class="btn-success rounded-pill shadow-lg btn btn-icon btn-lg p-2 jump-icon">
						<i class='ri-chat-3-line fs-22'></i>
					</span>
				</a>
			</div>
		}
	}
	<div id="layout-wrapper">
		@await Html.PartialAsync("_Header")
		@await Component.InvokeAsync("Menu")

		<div class="main-content">
			<div class="page-content">
				<div class="container-fluid">
					@await Html.PartialAsync("_PageTitle")
					@RenderBody()
				</div>
			</div>

			<div id="common-md-dialog" class="modal fade bs-example-modal-md" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
				<div class="modal-dialog modal-md">
					<div class="modal-content" id="common-md-dialogContent">
					</div>
				</div>
			</div>
			<div id="common-xl-dialog" class="modal fade bs-example-modal-xl" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
				<div class="modal-dialog modal-xl">
					<div class="modal-content" id="common-xl-dialogContent">
					</div>
				</div>
			</div>
			<div id="common-lg-dialog" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
				<div class="modal-dialog modal-lg">
					<div class="modal-content" id="common-lg-dialogContent">
					</div>
				</div>
			</div>
			<div id="common-dialog" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="false">
				<div class="modal-dialog">
					<div class="modal-content" id="common-dialogContent">
					</div>
				</div>
				<!-- /.modal-dialog -->
			</div>


		</div>
	</div>
	<footer class="footer">
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-6">
					@AppCommon.CurrentDate.Year © @AppCommon.ApplicationTitle.
				</div>
				<div class="col-sm-6">
					@*   <div class="text-sm-end d-none d-sm-block">
                        Powered by Arudha IT Solutions
                    </div> *@
				</div>
			</div>
		</div>
	</footer>
	@await Html.PartialAsync("_FooterScriptPartial")
	@RenderSection("scripts", required: false)
</body>
</html>

CFP.Web/Views/Shared/_Menu.cshtml
<div class="app-menu navbar-menu">
    <!-- LOGO -->
    <div class="navbar-brand-box">
         
        <!-- Light Logo-->
        <a href="/" class="logo logo-light">
            <img src="~/lib/images/logo-dark.png" class="headerLogo" style="height:50px;" />
        </a>
        <button type="button" class="btn btn-sm p-0 fs-20 header-item float-end btn-vertical-sm-hover" id="vertical-hover">
            <i class="ri-record-circle-line"></i>
        </button>
    </div>

    <div id="scrollbar">
        <div class="container-fluid">
            <div id="two-column-menu">
            </div>
            <ul class="navbar-nav" id="navbar-nav">
                <li class="menu-title"><span data-key="t-menu">Menu</span></li>

                

                <li class="nav-item">
                    <a class="nav-link menu-link" role="button">
                        <i class="ri-dashboard-2-line"></i> <span data-key="t-dashboards">Dashboards</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link menu-link" href="#sidebarDashboards" data-bs-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarDashboards">
                        <i class="ri-dashboard-2-line"></i> <span data-key="t-dashboards">Dashboards</span>
                    </a>
                    <div class="collapse menu-dropdown" id="sidebarDashboards">
                        <ul class="nav nav-sm flex-column">
                            <li class="nav-item">
                                <a href="/Dashboard/Analytics" class="nav-link" data-key="t-analytics"> Analytics </a>
                            </li>
                            <li class="nav-item">
                                <a href="/Dashboard/CRM" class="nav-link" data-key="t-crm"> CRM </a>
                            </li>
                            <li class="nav-item">
                                <a href="/" class="nav-link" data-key="t-ecommerce"> Ecommerce </a>
                            </li>
                            <li class="nav-item">
                                <a href="/Dashboard/Crypto" class="nav-link" data-key="t-crypto"> Crypto </a>
                            </li>
                            <li class="nav-item">
                                <a href="/Dashboard/Projects" class="nav-link" data-key="t-projects"> Projects </a>
                            </li>
                            <li class="nav-item">
                                <a href="/Dashboard/NFT" class="nav-link" data-key="t-nft"> NFT <span class="badge bg-pill bg-danger" data-key="t-new">New</span> </a>
                            </li>
                            <li class="nav-item">
                                <a href="/Dashboard/Job" class="nav-link" data-key="t-job">Job</a>
                            </li>
                        </ul>
                    </div>
                </li>




            </ul>
        </div>
    </div>
    <div class="sidebar-background"></div>
</div>
<div class="vertical-overlay"></div>